# Solution Exercise 2.3

In [2]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt

In [3]:
df = pd.read_csv("../data/supermarket_sales-Sheet1.csv")
df.head()

,Invoice ID,Branch,City,Customer type,Gender,Product line,Unit price,Quantity,Tax 5%,Total,Date,Time,Payment,cogs,gross margin percentage,gross income,Rating
0,750-67-8428,A,Yangon,Member,Female,Health and beauty,74.69,7,26.1415,548.9715,1/5/2019,13:08,Ewallet,522.83,4.761905,26.1415,9.1
1,226-31-3081,C,Naypyitaw,Normal,Female,Electronic accessories,15.28,5,3.8200,80.2200,3/8/2019,10:29,Cash,76.40,4.761905,3.8200,9.6
2,631-41-3108,A,Yangon,Normal,Male,Home and lifestyle,46.33,7,16.2155,340.5255,3/3/2019,13:23,Credit card,324.31,4.761905,16.2155,7.4
3,123-19-1176,A,Yangon,Member,Male,Health and beauty,58.22,8,23.2880,489.0480,1/27/2019,20:33,Ewallet,465.76,4.761905,23.2880,8.4
4,373-73-7910,A,Yangon,Normal,Male,Sports and travel,86.31,7,30.2085,634.3785,2/8/2019,10:37,Ewallet,604.17,4.761905,30.2085,5.3

In [4]:
# a) We want to conduct the study only in the Yangon city (for the entire exercise). Filter the data.
print(f"Cities before filtering: {df['City'].unique()}")

# Various ways of doing it. Depending on the task, we may want to create another dataframe e.g. df_yagon
# df = df[df['City'] == 'Yangon'] # Simplest approach
df = df[df['City'].isin(['Yangon'])] # If we wanted to filter multiple cities 
# df = df.loc[df['City'] == 'Yangon'] # More flexible for other filtering
# df = df.loc[df['City'].isin(['Yangon'])] # Similarly, more flexible with multiple cities
# df = df.query('City == "Yangon"') # Express conditions in a more SQL-like syntax.

print(f"Cities after filtering: {df['City'].unique()}")

Cities before filtering: ['Yangon' 'Naypyitaw' 'Mandalay']
Cities after filtering: ['Yangon']

In [5]:
# b) Look at some transactions with low ratings (<=4), some with high rating (>=9.9). Then filter these out for the rest of the exercise
df.loc[df['Rating']<=4].head(10)

,Invoice ID,Branch,City,Customer type,Gender,Product line,Unit price,Quantity,Tax 5%,Total,Date,Time,Payment,cogs,gross margin percentage,gross income,Rating
618,828-46-6863,A,Yangon,Member,Male,Food and beverages,98.53,6,29.5590,620.7390,1/23/2019,11:22,Credit card,591.18,4.761905,29.5590,4.0
790,651-96-5970,A,Yangon,Normal,Male,Fashion accessories,46.41,1,2.3205,48.7305,3/3/2019,20:06,Credit card,46.41,4.761905,2.3205,4.0

In [6]:
df.loc[df['Rating']>=9.9].head(10)

,Invoice ID,Branch,City,Customer type,Gender,Product line,Unit price,Quantity,Tax 5%,Total,Date,Time,Payment,cogs,gross margin percentage,gross income,Rating
23,636-48-8204,A,Yangon,Normal,Male,Electronic accessories,34.56,5,8.6400,181.4400,2/17/2019,11:15,Ewallet,172.80,4.761905,8.6400,9.9
103,212-62-1842,A,Yangon,Normal,Male,Food and beverages,58.26,6,17.4780,367.0380,3/28/2019,16:44,Cash,349.56,4.761905,17.4780,9.9
188,400-60-7251,A,Yangon,Normal,Male,Home and lifestyle,74.07,1,3.7035,77.7735,2/10/2019,12:50,Ewallet,74.07,4.761905,3.7035,9.9
194,831-07-6050,A,Yangon,Normal,Male,Electronic accessories,32.71,5,8.1775,171.7275,3/19/2019,11:30,Credit card,163.55,4.761905,8.1775,9.9
384,662-72-2873,A,Yangon,Normal,Female,Food and beverages,40.94,5,10.2350,214.9350,1/6/2019,13:58,Ewallet,204.70,4.761905,10.2350,9.9
387,725-56-0833,A,Yangon,Normal,Female,Health and beauty,32.32,10,16.1600,339.3600,2/20/2019,16:49,Credit card,323.20,4.761905,16.1600,10.0
762,410-67-1709,A,Yangon,Member,Female,Fashion accessories,63.88,8,25.5520,536.5920,1/20/2019,17:48,Ewallet,511.04,4.761905,25.5520,9.9
873,166-19-2553,A,Yangon,Member,Male,Sports and travel,89.06,6,26.7180,561.0780,1/18/2019,17:26,Cash,534.36,4.761905,26.7180,9.9

In [7]:
df = df.loc[(df['Rating']>4) & (df['Rating']<9.9)]
# or
# df = df.loc[~(df['Rating']<=4) & ~(df['Rating']>=9.9)]

In [8]:
# c) Calculate the Total price in a new column, computed as Unit price * quantity + Tax 5%. Compare with the "Total" column
df['Total price'] = df.apply(lambda row: row['Unit price'] * row['Quantity'] + row['Tax 5%'], axis=1)
# or simply
# df['Total price'] = df['Unit price'] * df['Quantity'] + df['Tax 5%']
df[['Total','Total price']].head()

      Total  Total price
0  548.9715     548.9715
2  340.5255     340.5255
3  489.0480     489.0480
4  634.3785     634.3785
6  433.6920     433.6920

In [9]:
# d) A 10% discount on the total price was given to the members. Add that to a new column. Use lambda function.
df['Total price discount'] = df.apply(lambda row: row['Total price']*0.9 if row['Customer type']=='Member' else row['Total price'], axis=1)
df.head()

,Invoice ID,Branch,City,Customer type,Gender,Product line,Unit price,Quantity,Tax 5%,Total,Date,Time,Payment,cogs,gross margin percentage,gross income,Rating,Total price,Total price discount
0,750-67-8428,A,Yangon,Member,Female,Health and beauty,74.69,7,26.1415,548.9715,1/5/2019,13:08,Ewallet,522.83,4.761905,26.1415,9.1,548.9715,494.07435
2,631-41-3108,A,Yangon,Normal,Male,Home and lifestyle,46.33,7,16.2155,340.5255,3/3/2019,13:23,Credit card,324.31,4.761905,16.2155,7.4,340.5255,340.52550
3,123-19-1176,A,Yangon,Member,Male,Health and beauty,58.22,8,23.2880,489.0480,1/27/2019,20:33,Ewallet,465.76,4.761905,23.2880,8.4,489.0480,440.14320
4,373-73-7910,A,Yangon,Normal,Male,Sports and travel,86.31,7,30.2085,634.3785,2/8/2019,10:37,Ewallet,604.17,4.761905,30.2085,5.3,634.3785,634.37850
6,355-53-5943,A,Yangon,Member,Female,Electronic accessories,68.84,6,20.6520,433.6920,2/25/2019,14:36,Ewallet,413.04,4.761905,20.6520,5.8,433.6920,390.32280