In [12]:
import numpy as np
import pandas as pd

In [13]:
# a)
data = pd.read_csv("iris_to_clean.csv")
data.head(10)

,measurement.number,sepal.length,sepal.width,petal.length,petal.width,variety
0,1,5.1,3.5,1.4,0.2,Setosa
1,2,4.9,3.0,1.4,0.2,Setosa
2,3,4.7,3.2,1.3,0.2,Setosa
3,4,4.6,3.1,1.5,0.2,Setosa
4,5,5.0,3.6,1.4,0.2,Setosa
5,6,5.4,3.9,1.7,0.4,Setosa
6,7,4.6,3.4,1.4,0.3,Setosa
7,8,5.0,3.4,1.5,0.2,Setosa
8,9,4.4,2.9,1.4,0.2,Setosa
9,10,4.9,3.1,1.5,0.1,Setosa

In [14]:
data.describe()

,measurement.number,sepal.length,sepal.width,petal.length,petal.width
count,154.000000,154.000000,153.000000,152.000000,154.000000
mean,74.902597,6.198052,3.211111,4.080921,1.316234
std,43.030886,4.282499,1.984000,4.204818,1.619064
min,1.000000,4.300000,2.000000,1.000000,0.100000
25%,39.250000,5.100000,2.800000,1.600000,0.300000
50%,73.500000,5.800000,3.000000,4.400000,1.300000
75%,111.750000,6.400000,3.300000,5.100000,1.800000
max,150.000000,58.000000,27.000000,51.000000,19.000000

In [15]:
# b)
data.duplicated().sum()

np.int64(4)

In [16]:
no_duplicates = data.copy()
no_duplicates.drop_duplicates(inplace=True)

print(data.shape[0])
print(no_duplicates.shape[0])

154
150

In [17]:
# c)
no_duplicates.sort_values("sepal.length") # none
no_duplicates.sort_values("sepal.width") # 1
no_duplicates.sort_values("petal.length") # 2
# no_duplicates.sort_values("petal.width") # none
# no_duplicates.sort_values("variety") # none

,measurement.number,sepal.length,sepal.width,petal.length,petal.width,variety
22,23,4.6,3.6,1.0,0.2,Setosa
13,14,4.3,3.0,1.1,0.1,Setosa
14,15,5.8,4.0,1.2,0.2,Setosa
35,36,5.0,3.2,1.2,0.2,Setosa
16,17,5.4,3.9,1.3,0.4,Setosa
...,...,...,...,...,...,...
126,123,7.7,2.8,6.7,2.0,Virginica
122,119,7.7,2.6,6.9,2.3,Virginica
146,143,58.0,27.0,51.0,19.0,Virginica
36,37,5.5,3.5,NaN,0.2,Setosa
134,131,7.4,2.8,NaN,1.9,Virginica

In [18]:
# lines_with_empty_entries_index = []
# for line in no_duplicates.values:
#     print(line)
#     print(line[1])
#     for val in line:
#         # print(val)
#         if str(val) == "NaN":
#             lines_with_empty_entries_index.append(line[0])
#             break
# print(lines_with_empty_entries_index)

In [19]:
l = ["measurement.number", "sepal.length", "sepal.width", "petal.length", "petal.width", "variety"]
no_duplicates[no_duplicates[l].isnull().any(axis=1)]

,measurement.number,sepal.length,sepal.width,petal.length,petal.width,variety
26,27,5.0,NaN,1.6,0.4,Setosa
36,37,5.5,3.5,NaN,0.2,Setosa
134,131,7.4,2.8,NaN,1.9,Virginica

In [26]:
no_duplicates.dropna(how='any', inplace=True)
no_duplicates[no_duplicates[l].isnull().any(axis=1)]

Empty DataFrame
Columns: [measurement.number, sepal.length, sepal.width, petal.length, petal.width, variety]
Index: []

In [33]:
descr = no_duplicates.describe()
descr

,measurement.number,sepal.length,sepal.width,petal.length,petal.width
count,147.000000,147.000000,147.000000,147.000000,147.000000
mean,75.714286,6.195918,3.219048,4.085714,1.323129
std,43.346011,4.380027,2.022488,4.270286,1.652233
min,1.000000,4.300000,2.000000,1.000000,0.100000
25%,39.500000,5.100000,2.800000,1.600000,0.300000
50%,76.000000,5.800000,3.000000,4.400000,1.300000
75%,112.500000,6.400000,3.300000,5.100000,1.800000
max,150.000000,58.000000,27.000000,51.000000,19.000000

In [ ]:
# d) haven't finished.
l2 = ["measurement.number", "sepal.length", "sepal.width", "petal.length", "petal.width"]
for i in l2:
    print(descr[i])

count    147.000000
mean      75.714286
std       43.346011
min        1.000000
25%       39.500000
50%       76.000000
75%      112.500000
max      150.000000
Name: measurement.number, dtype: float64
count    147.000000
mean       6.195918
std        4.380027
min        4.300000
25%        5.100000
50%        5.800000
75%        6.400000
max       58.000000
Name: sepal.length, dtype: float64
count    147.000000
mean       3.219048
std        2.022488
min        2.000000
25%        2.800000
50%        3.000000
75%        3.300000
max       27.000000
Name: sepal.width, dtype: float64
count    147.000000
mean       4.085714
std        4.270286
min        1.000000
25%        1.600000
50%        4.400000
75%        5.100000
max       51.000000
Name: petal.length, dtype: float64
count    147.000000
mean       1.323129
std        1.652233
min        0.100000
25%        0.300000
50%        1.300000
75%        1.800000
max       19.000000
Name: petal.width, dtype: float64

In [ ]:
# # Save the cleaned dataset, check in excel or else that it seems fine
# df.to_csv('../data/iris_cleaned.csv', index=False)