In [62]:
import numpy as np
import pandas as pd

df = pd.read_csv("iris_cleaned.csv")

In [63]:
df.describe()

,measurement.number,sepal.length,sepal.width,petal.length,petal.width
count,149.000000,149.000000,149.000000,149.000000,149.000000
mean,75.046980,5.843624,3.058389,3.754362,1.194631
std,43.234955,0.830851,0.435595,1.746095,0.762622
min,1.000000,4.300000,2.000000,1.000000,0.100000
25%,38.000000,5.100000,2.800000,1.600000,0.300000
50%,75.000000,5.800000,3.000000,4.300000,1.300000
75%,112.000000,6.400000,3.300000,5.100000,1.800000
max,150.000000,7.900000,4.400000,6.900000,2.500000

In [64]:
# a)
df["petal_ratio"] = df.apply(lambda i: i["petal.length"]/i["petal.width"], axis=1)
df

,measurement.number,sepal.length,sepal.width,petal.length,petal.width,variety,petal_ratio
0,1,5.1,3.5,1.4,0.2,Setosa,7.000000
1,2,4.9,3.0,1.4,0.2,Setosa,7.000000
2,3,4.7,3.2,1.3,0.2,Setosa,6.500000
3,4,4.6,3.1,1.5,0.2,Setosa,7.500000
4,5,5.0,3.6,1.4,0.2,Setosa,7.000000
...,...,...,...,...,...,...,...
144,146,6.7,3.0,5.2,2.3,Virginica,2.260870
145,147,6.3,2.5,5.0,1.9,Virginica,2.631579
146,148,6.5,3.0,5.2,2.0,Virginica,2.600000
147,149,6.2,3.4,5.4,2.3,Virginica,2.347826
148,150,5.9,3.0,5.1,1.8,Virginica,2.833333

In [66]:
# b)
numerical_values = ["sepal.length", "sepal.width", "petal.length", "petal.width"]

def z_score_normalization(x, mean, standard_deviation):
    return (x-mean)/standard_deviation

# std_dev = df["sepal.length"].std()
# m = df["sepal.width"].mean()
# print(std_dev, m)
# data = {"index":[]}
st = pd.DataFrame()
for col in numerical_values:
    m = df[col].mean()
    std_dev = df[col].std()
    z = df.apply(lambda i: z_score_normalization(i[col], m, std_dev), axis=1)
    st[f"standardized.{col}"] = z

st
st.pivot_table(index="standardized.sepal.length", values=["standardized.sepal.length", "standardized.sepal.width", "standardized.petal.length", "standardized.petal.width"])

,standardized.petal.length,standardized.petal.width,standardized.sepal.length,standardized.sepal.width
standardized.sepal.length,,,,
-1.857883,-1.520170,-1.435351,-1.857883,-0.134045
-1.737524,-1.386539,-1.304225,-1.737524,-0.057521
-1.617166,-1.405629,-1.173098,-1.617166,-1.741041
-1.496807,-1.391311,-1.271443,-1.496807,0.612061
-1.376449,-1.319723,-1.304225,-1.376449,0.325097
-1.256090,-1.245271,-1.304225,-1.256090,0.279183
-1.135732,-0.852013,-0.845282,-1.135732,-0.248830
-1.015373,-1.096368,-1.002634,-1.015373,0.095526
-0.895015,-1.163820,-1.041972,-0.895015,0.962794
-0.774656,-0.961782,-0.943627,-0.774656,0.841631
-0.654298,-1.291088,-1.304225,-0.654298,1.472951
-0.533939,-0.985644,-0.888991,-0.533939,1.128595
-0.413581,-0.072041,-0.386339,-0.413581,-0.494799
-0.293222,0.255219,0.291148,-0.293222,-0.554925
-0.172864,-0.095563,-0.124086,-0.172864,0.095526
-0.052505,0.083408,0.160021,-0.052505,-0.325354
0.067853,0.541573,0.662673,0.067853,0.019003
0.188212,0.512937,0.400420,0.188212,-0.746234
0.308570,0.570208,0.291148,0.308570,-0.478401
0.428929,0.570208,0.695455,0.428929,-0.535794
0.549287,0.789745,0.808369,0.549287,-0.465647
0.669646,0.803381,0.887461,0.669646,-0.232432
0.790004,0.850834,0.924926,0.790004,-0.134045
0.910363,0.427031,0.203730,0.910363,-0.248830
1.030721,0.863720,1.006880,1.030721,-0.019259
1.151079,0.942467,0.968635,1.151079,-0.134045
1.271438,0.870879,1.121616,1.271438,0.152919
1.391796,0.541573,0.269293,1.391796,0.325097
1.512155,1.228820,1.187179,1.512155,-0.134045
1.632513,1.267001,1.012344,1.632513,0.478144
1.752872,1.457903,0.793800,1.752872,-0.363616
1.873230,0.197949,0.924926,1.873230,-0.593186
2.113947,1.629715,1.187179,2.113947,-0.134045
2.234306,1.629715,1.318306,2.234306,-0.019259
2.475023,1.515174,1.056053,2.475023,1.702522