In [47]:
import numpy as np
import pandas as pd

df = pd.read_csv("supermarket_sales-Sheet1.csv")

In [48]:
df.columns.values

<StringArray>
[             'Invoice ID',                  'Branch',
                    'City',           'Customer type',
                  'Gender',            'Product line',
              'Unit price',                'Quantity',
                  'Tax 5%',                   'Total',
                    'Date',                    'Time',
                 'Payment',                    'cogs',
 'gross margin percentage',            'gross income',
                  'Rating']
Length: 17, dtype: str

In [49]:
df.describe()

,Unit price,Quantity,Tax 5%,Total,cogs,gross margin percentage,gross income,Rating
count,1000.000000,1000.000000,1000.000000,1000.000000,1000.00000,1000.000000,1000.000000,1000.00000
mean,55.672130,5.510000,15.379369,322.966749,307.58738,4.761905,15.379369,6.97270
std,26.494628,2.923431,11.708825,245.885335,234.17651,0.000000,11.708825,1.71858
min,10.080000,1.000000,0.508500,10.678500,10.17000,4.761905,0.508500,4.00000
25%,32.875000,3.000000,5.924875,124.422375,118.49750,4.761905,5.924875,5.50000
50%,55.230000,5.000000,12.088000,253.848000,241.76000,4.761905,12.088000,7.00000
75%,77.935000,8.000000,22.445250,471.350250,448.90500,4.761905,22.445250,8.50000
max,99.960000,10.000000,49.650000,1042.650000,993.00000,4.761905,49.650000,10.00000

In [50]:
# a)
s = pd.DataFrame(df.groupby("Payment")["Quantity"].sum())
m = pd.DataFrame(df.groupby("Payment")["Quantity"].mean())
c = pd.DataFrame(df.groupby("Payment")["Quantity"].count())


display("---SUM---", s, "---MEAN---", m, "---COUNT---", c)

'---SUM---'

             Quantity
Payment
Cash             1896
Credit card      1722
Ewallet          1892

'---MEAN---'

             Quantity
Payment
Cash         5.511628
Credit card  5.536977
Ewallet      5.484058

'---COUNT---'

             Quantity
Payment
Cash              344
Credit card       311
Ewallet           345

In [51]:
# b)
# pt = pd.pivot_table(m)
quantity_pivot = df.pivot_table(values='Quantity', index='Payment', aggfunc='mean')
display(quantity_pivot)

             Quantity
Payment
Cash         5.511628
Credit card  5.536977
Ewallet      5.484058

In [56]:
# c)
customer_pivot = df.pivot_table(values="Quantity", index="Customer type", aggfunc="count")
city_pivot = df.pivot_table(values="Quantity", index="City", aggfunc="count")

display(customer_pivot, city_pivot)

               Quantity
Customer type
Member              501
Normal              499

           Quantity
City
Mandalay        332
Naypyitaw       328
Yangon          340